### ISSUE TITLE
Packagist needs manual updates 

### ISSUE THREAD

**Issue by jjroelofs** [dxpr/lightning_dxpr_project#10]
Every time I update the dev branch, or when I tag a new release, I need to manually update on packagist before the change is published on packagist.

Would be great if this was fully automated.

**Comment by hoatle** [comment]
the problem is fixed, it should work now https://packagist.org/packages/dxpr/lightning-dxpr-project

**Comment by hoatle** [comment]
https://packagist.org/packages/dxpr/lightning_dxpr is fixed, too.

Note: you need to delete the versions associated with deleted branches manually as I see that packagist does not delete it automatically.

**Comment by jjroelofs** [comment]
ok thx!
