### ISSUE TITLE
DXPR access token is not installed on the docker service

### ISSUE THREAD

**Issue by mhmelshaaerdxpr** [dxpr/lightning_dxpr_project#19]
After configuring the CI/CD stack, check this #16, I have an issue regarding the installation script which fails because of the DXPR access token is not installed, or this is what I understand from the error log.

![accesstokenerr](https://user-images.githubusercontent.com/70699173/115344184-455bf280-a1ad-11eb-9e7d-949b478e88f3.PNG)

One thing to note is that this is working ok when running locally on my machine. You can also check the linked PR for the #18 issue.

**Comment by hoatle** [comment]
let me check on this then

**Comment by hoatle** [comment]
I updated the access token with dxpr_builder_e access, please retry now.

**Comment by jjroelofs** [comment]
Fixed by replacing the token with Shaaer's token. Thx @hoatle
